
let p = prompt('Nhập bán kính đường tròn')
console.log('Chu vi đường tròn là' + Math.round(Math.PI*2*p*100)/100)
let ten = prompt('Nhập tên')
let tuoi = prompt('Tuổi')
let lamgi = prompt('Làm gì')
let odau = prompt('Ở đâu')
alert ('có sợ bị hacker mò vào nhà không')
console.log('Nhập vô xong viết lại ra kiểu: ' + ten + ' ' + tuoi + ' ' + lamgi + ' '+ odau)
let a = parseInt(prompt('Nhập vào số thứ 1'))
let b = parseInt(prompt('Nhập số thứ 2'))
let c = parseInt(prompt('Số thứ 3'))
let d = parseInt(prompt('Số 4'))
let e = parseInt(prompt('5'))
console.log('Khổ quá vừa làm vừa chơi lười tí thì sao')
console.log('Tổng' + Math.round(a+b+c+d+e))
console.log('Tích' +Math.round(a*b*c*d*e))
console.log('Max' + Math.max(a, b, c, d, e))
console.log('Min' + Math.min(a, b, c, d, e))
console.log('Thua r :((')